 cat  files/index.html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>
[root@master ~]# cat site.yaml
---
- name: Install and start Apache HTTPD
  hosts: all
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    - name: correct index.html is present
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
